#!/usr/bin/env ruby

Vagrant.configure("2") do |config|
  # 18.04
  config.vm.network "forwarded_port", guest: 22, host: 22220, id: "ssh"
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20200206.0.0"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end
  config.vm.provision "file", source: "~/.vimrc", destination: "~/.vimrc"
  config.vm.provision "file", source: "~/.vim/", destination: "~/"
  config.vm.provision :shell, path: "install-mininet.sh"
  config.vm.provision :shell, path: "install-ryu.sh"
end
